services:
  backend:
    build:
      context: ./server
      dockerfile: ./server/Dockerfile
    image: arkad23/propapp_backend:latest
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    container_name: PropApp_backend

  frontend:
    build:
      context: ./client
      dockerfile: ./client/Dockerfile
    image: arkad23/propapp_frontend:latest
    ports:
      - '3000:3000'
    env_file:
      - ./client/.env.local
    volumes:
      - ./client:/app
    container_name: PropApp_frontend
    depends_on:
      - backend
