import { Navbar } from "@/components/Navbar.jsx";
import StoreProvider from "./storeProvider";

export const metadata = {
  title: "PropApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Navbar />
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
