-- AlterTable
ALTER TABLE "Listing" ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "bathrooms" DROP NOT NULL,
ALTER COLUMN "bedrooms" DROP NOT NULL,
ALTER COLUMN "parking" DROP NOT NULL,
ALTER COLUMN "offer" DROP NOT NULL,
ALTER COLUMN "Realtor" DROP NOT NULL;
