name: Build and Deploy Frontend and Backend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Copy project files to EC2
      run: |
        rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/Prop_app/

    - name: Deploy on EC2
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/Prop_app
          docker compose down --remove-orphans
          docker compose pull || true
          docker compose build --no-cache
          docker compose up -d --remove-orphans
          docker system prune -af
        EOF
